from .UserInfoView import *
from .SubjectView import *
from .TestView import *
from .ProfileUpdateView import *
from .McqQuestionView import *
from .EssayQuestionView import *
from .RegistrationView import *
from .LoginView import *
from .UP_mcqExamView import *
from .UP_essayExamView import *
from .ReviewView import *
