# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 20:11
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(7), django.core.validators.MinValueValidator(7)])),
                ('user_name', models.CharField(max_length=200)),
                ('user_contact', models.CharField(max_length=200)),
                ('user_image', models.ImageField(blank=True, upload_to='profile_pics')),
                ('user_email', models.EmailField(max_length=254)),
                ('user_status', models.BooleanField(default=False)),
                ('user_password', models.CharField(max_length=11, validators=[django.core.validators.MinValueValidator(7)])),
                ('approver', models.CharField(max_length=200)),
                ('datetime', models.DateTimeField()),
            ],
        ),
    ]
