# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 20:32
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_userinfo_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='user_contact',
            field=models.CharField(max_length=11, validators=[django.core.validators.MaxValueValidator(7), django.core.validators.MinValueValidator(7)]),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_name',
            field=models.CharField(max_length=50),
        ),
    ]
