# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 20:39
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_auto_20171103_0232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(3)])),
                ('subject_name', models.CharField(max_length=20)),
                ('mcq_total_questions', models.IntegerField()),
                ('essay_total_questions', models.IntegerField()),
                ('approver', models.CharField(max_length=50)),
                ('datetime', models.DateTimeField()),
            ],
        ),
    ]
