# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_auto_20171103_0240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='essay_total_questions',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='subject',
            name='mcq_total_questions',
            field=models.IntegerField(),
        ),
    ]
