# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 21:06
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_auto_20171103_0301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('test_id', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxLengthValidator(3), django.core.validators.MinLengthValidator(3)])),
                ('test_name', models.CharField(max_length=20)),
                ('test_totalmarks', models.IntegerField()),
                ('test_totaltimes', models.IntegerField()),
                ('test_type', models.IntegerField()),
                ('approver', models.CharField(max_length=50)),
                ('datetime', models.DateTimeField()),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.Subject')),
            ],
        ),
    ]
