# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 21:22
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='McqQuestion',
            fields=[
                ('mcq_question_id', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxLengthValidator(2), django.core.validators.MinLengthValidator(2)])),
                ('mcq_question', models.CharField(max_length=100)),
                ('mcq_option1', models.IntegerField()),
                ('mcq_option2', models.IntegerField()),
                ('mcq_option3', models.IntegerField()),
                ('mcq_option4', models.IntegerField()),
                ('mcq_right_answer', models.IntegerField()),
                ('approver', models.CharField(max_length=50)),
                ('datetime', models.DateTimeField()),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.Test')),
            ],
        ),
    ]
