# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 21:32
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_mcqquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='EssayQuestion',
            fields=[
                ('essay_question_id', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxLengthValidator(2), django.core.validators.MinLengthValidator(2)])),
                ('essay_question', models.TextField()),
                ('essay_question_marks', models.IntegerField()),
                ('approver', models.CharField(max_length=50)),
                ('datetime', models.DateTimeField()),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.Test')),
            ],
        ),
    ]
