# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 22:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0010_mcqanswer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mcqanswer',
            name='id',
        ),
        migrations.AlterField(
            model_name='mcqanswer',
            name='test_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, to='exam.Test'),
        ),
        migrations.AlterField(
            model_name='mcqanswer',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='exam.UserInfo'),
        ),
    ]
