# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 22:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0013_auto_20171103_0410'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mcqanswer',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='mcqanswer',
            name='test_id',
        ),
        migrations.RemoveField(
            model_name='mcqanswer',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='McqAnswer',
        ),
    ]
