# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0014_auto_20171103_0430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcqquestion',
            name='mcq_option1',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mcqquestion',
            name='mcq_option2',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mcqquestion',
            name='mcq_option3',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mcqquestion',
            name='mcq_option4',
            field=models.CharField(max_length=50),
        ),
    ]
