# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-03 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0015_auto_20171103_0445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essayquestion',
            name='essay_question_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mcqquestion',
            name='mcq_question_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_contact',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_password',
            field=models.CharField(max_length=11),
        ),
    ]
