# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-03 18:20
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0016_auto_20171103_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essayquestion',
            name='essay_question_id',
            field=models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxLengthValidator(2), django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='mcqquestion',
            name='mcq_question_id',
            field=models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxLengthValidator(2), django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_id',
            field=models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(3)]),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_id',
            field=models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxLengthValidator(3), django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_contact',
            field=models.CharField(max_length=11, validators=[django.core.validators.MaxValueValidator(7), django.core.validators.MinValueValidator(7)]),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_id',
            field=models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(7), django.core.validators.MinValueValidator(7)]),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_password',
            field=models.CharField(max_length=11, validators=[django.core.validators.MinValueValidator(7)]),
        ),
    ]
