# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-03 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0017_auto_20171104_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='approver',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics'),
        ),
    ]
