# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-03 22:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0018_auto_20171104_0414'),
        ('exam', '0018_auto_20171104_0219'),
    ]

    operations = [
    ]
