# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-03 22:39
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0019_merge_20171104_0436'),
    ]

    operations = [
        migrations.CreateModel(
            name='EssayQuestion',
            fields=[
                ('essay_question_id', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxLengthValidator(2), django.core.validators.MinLengthValidator(2)])),
                ('essay_question', models.TextField()),
                ('essay_question_marks', models.IntegerField()),
                ('approver', models.CharField(blank=True, max_length=50, null=True)),
                ('datetime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='McqQuestion',
            fields=[
                ('mcq_question_id', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxLengthValidator(2), django.core.validators.MinLengthValidator(2)])),
                ('mcq_question', models.CharField(max_length=100)),
                ('mcq_option1', models.CharField(max_length=50)),
                ('mcq_option2', models.CharField(max_length=50)),
                ('mcq_option3', models.CharField(max_length=50)),
                ('mcq_option4', models.CharField(max_length=50)),
                ('mcq_right_answer', models.IntegerField()),
                ('approver', models.CharField(blank=True, max_length=50, null=True)),
                ('datetime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(3)])),
                ('subject_name', models.CharField(max_length=20)),
                ('mcq_total_questions', models.IntegerField()),
                ('essay_total_questions', models.IntegerField()),
                ('approver', models.CharField(blank=True, max_length=50, null=True)),
                ('datetime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('test_id', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxLengthValidator(3), django.core.validators.MinLengthValidator(3)])),
                ('test_name', models.CharField(max_length=20)),
                ('test_totalmarks', models.IntegerField()),
                ('test_totaltimes', models.IntegerField()),
                ('test_type', models.IntegerField()),
                ('approver', models.CharField(blank=True, max_length=50, null=True)),
                ('datetime', models.DateTimeField()),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.Subject')),
            ],
        ),
        migrations.AddField(
            model_name='mcqquestion',
            name='test_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.Test'),
        ),
        migrations.AddField(
            model_name='essayquestion',
            name='test_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.Test'),
        ),
    ]
