# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-04 16:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0020_auto_20171104_0439'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='essay_total_questions',
            new_name='essay_total_test',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='mcq_total_questions',
            new_name='mcq_total_test',
        ),
    ]
