# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-04 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0021_auto_20171104_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='test_total_questions',
            field=models.IntegerField(null=True),
        ),
    ]
