# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-06 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0022_test_test_total_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='user_image',
            field=models.FileField(blank=True, null=True, upload_to='profile_pics'),
        ),
    ]
