# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0023_auto_20171106_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='test_total_questions',
            field=models.IntegerField(),
        ),
    ]
